### ISSUE TITLE
问题 | 反编译后发现中文字符串乱码

### ISSUE THREAD

**Issue by qianniaoge** [2539469416/0Xdecompile#1]
1.正常使用对0Xdecompile工具目标JAR程序包进行逆向工作，发现对中文字符串内容无法正常显示，是乱码状态。

**Comment by 2539469416** [comment]
应该是编码的问题，我之后解决这个问题

**Comment by 2539469416** [comment]
> 1.正常使用对0Xdecompile工具目标JAR程序包进行逆向工作，发现对中文字符串内容无法正常显示，是乱码状态。

着急吗

**Comment by 2539469416** [comment]
你好，感谢使用，问题已经解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "2539469416/0Xdecompile"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月14日(星期五) 下午2:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [2539469416/0Xdecompile] 问题 | 反编译后发现中文字符串乱码 (Issue #1)





 
Closed #1 as completed.
